theme: jekyll-theme-minimal
title: dejavu
description: collection of useful snippets, commands and tips & tricks for my daily work
navigation:
  - title: Home
    url: /
  - title: Ansible
    url: ansible/ansible
  - title: Bash
    url: bash/bash
  - title: Docker
    url: docker/docker
  - title: Golang
    url: go/go
  - title: Kubernetes
    url: kubernetes/kubernetes
  - title: Git
    url: git/git
  - title: Linux
    url: linux/linux
  - title: Python
    url: python/python
  - title: Podman
    url: podman/podman
  - title: RPM
    url: rpm/rpm
  - title: VIM
    url: vim/vim
