theme: jekyll-theme-minimal
title: FalcoSuessgotts Wiki
description: collection of snippets, commands and useful tips
navigation:
  - title: Home
    url: /
  - title: Ansible
    url: ansible/ansible
